### ISSUE TITLE
Jackson Fails to Parse close_time_human in LedgerHeader

### ISSUE THREAD

**Issue by nkramer44** [XRPLF/xrpl4j#114]
_Moved from RippleX Forum issue_

> When querying the transaction of the block I specified, it will prompt that the time field Jackson has failed to parse, because the time of the entity class is represented by ZonedDateTime.
![截屏2021-06-16 下午3 15 08](https://user-images.githubusercontent.com/19825873/122984689-49ea8600-d36b-11eb-92ef-7338d5da0ccc.png)

**Comment by Smilestate** [comment]
When I used xrpl4j, I found several abnormal problems when parsing the block. First of all, when I use the xrplClient.ledger method to obtain the current block information, there is no abnormal information, but when I use the above method to obtain the verified ledger index or the specified ledger index, xrpl4j will throw a parsing exception, which cannot The parsed field is close_time_human.

setting：JDK1.8

Exception in thread "main" org.xrpl.xrpl4j.client.JsonRpcClientErrorException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.ZonedDateTime` from String "2021-Jun-11 09:06:10.000000000 UTC": Failed to deserialize java.time.ZonedDateTime: (java.time.format.DateTimeParseException) Text '2021-Jun-11 09:06:10.000000000 UTC' could not be parsed at index 5
 at [Source: (StringReader); line: 1, column: 168] (through reference chain: org.xrpl.xrpl4j.model.client.ledger.ImmutableLedgerResult$Json["ledger"]->org.xrpl.xrpl4j.model.ledger.ImmutableLedgerHeader$Json["close_time_human"])
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:120)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:75)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy21.send(Unknown Source)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:93)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:75)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy21.send(Unknown Source)
	at org.xrpl.xrpl4j.client.XrplClient.ledger(XrplClient.java:365)
	at com.test.demo.GetAccountInfo.main(GetAccountInfo.java:83)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.ZonedDateTime` from String "2021-Jun-11 09:06:10.000000000 UTC": Failed to deserialize java.time.ZonedDateTime: (java.time.format.DateTimeParseException) Text '2021-Jun-11 09:06:10.000000000 UTC' could not be parsed at index 5
 at [Source: (StringReader); line: 1, column: 168] (through reference chain: org.xrpl.xrpl4j.model.client.ledger.ImmutableLedgerResult$Json["ledger"]->org.xrpl.xrpl4j.model.ledger.ImmutableLedgerHeader$Json["close_time_human"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1851)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1079)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._fromString(InstantDeserializer.java:288)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:209)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:50)
	at com.fasterxml.jackson.databind.deser.std.ReferenceTypeDeserializer.deserialize(ReferenceTypeDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:225)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1398)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:225)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1398)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:118)
	... 11 more
Caused by: java.time.format.DateTimeParseException: Text '2021-Jun-11 09:06:10.000000000 UTC' could not be parsed at index 5
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._fromString(InstantDeserializer.java:282)
	... 32 more

**Comment by sappenin** [comment]
I'm unable to reproduce this (I added your date/time String to [this unit test,](https://github.com/XRPLF/xrpl4j/blob/main/xrpl4j-model/src/test/java/org/xrpl/xrpl4j/model/ledger/LedgerHeaderJsonTests.java#L33), but it worked fine. I am also am not able to get [this IT](https://github.com/XRPLF/xrpl4j/blob/main/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/LedgerResultIT.java#L18) to fail).

That said, I suspect there's a problem with the Feign client's configured ObjectMapper.

So, could you send me an actual code-snipped that's failing for you? It would be helpful if it specified an actual LedgerIndex on Main or testnet so I can try to see what's happening.

Thanks!

**Comment by Smilestate** [comment]
LedgerResult ledger = xrplClient.ledger(LedgerRequestParams.builder().transactions(true).ledgerIndex(new LedgerIndex("64190089")).build());

**Comment by Smilestate** [comment]
I used your test case, and there is also a time resolution problem?
Is there something wrong with the jar I am using? Or is the version of my jdk too low? Or caused by other factors, the current docking with xrp is basically completed, and the interface temporarily uses http requests, but I still want to use xrplclient for docking, which feels very convenient and efficient. But I still have a question. Will access be restricted if I use xrplclient?

**Comment by Smilestate** [comment]
ZonedDateTime.parse("2020-Mar-24 01:41:11.000000000 UTC",
                DateTimeFormatter.ofPattern("yyyy-MMM-dd HH:mm:ss.SSSSSSSSS z")).withZoneSameLocal(ZoneId.of("UTC"))
Mainly because of the problem with this time parsing code. 
You can look at your jdk version, or other jars. I think the client you provide should also be compatible with this aspect. I look forward to your reply!

**Comment by nkramer44** [comment]
I'm unable to reproduce either. I ran your code and had no problem:

```java
XrplClient xrplClient = new XrplClient(HttpUrl.get("https://s1.ripple.com:51234/"));
final LedgerResult ledger = xrplClient.ledger(
  LedgerRequestParams.builder()
    .transactions(true)
    .ledgerIndex(LedgerIndex.of("64190089"))
    .build()
);
logger.info("Ledger: " + ledger);
```

Are you sure you are using xrpl4j v2.0.0? Which JDK are you running on? 

I would say it has something to do with your Jackson `ObjectMapper`, but if this
```java
ZonedDateTime.parse("2020-Mar-24 01:41:11.000000000 UTC",
DateTimeFormatter.ofPattern("yyyy-MMM-dd HH:mm:ss.SSSSSSSSS z")).withZoneSameLocal(ZoneId.of("UTC"))
```
throws an exception for you, then it must be something else.

**Comment by Smilestate** [comment]
What environment variables do you configure?
My operating environment is as follows:
1. jdk1.8
2.jackson 2.12.3

**Comment by Smilestate** [comment]
> I'm unable to reproduce either. I ran your code and had no problem:
> 
> ```java
> XrplClient xrplClient = new XrplClient(HttpUrl.get("https://s1.ripple.com:51234/"));
> final LedgerResult ledger = xrplClient.ledger(
>   LedgerRequestParams.builder()
>     .transactions(true)
>     .ledgerIndex(LedgerIndex.of("64190089"))
>     .build()
> );
> logger.info("Ledger: " + ledger);
> ```
> 
> Are you sure you are using xrpl4j v2.0.0? Which JDK are you running on?
> 
> I would say it has something to do with your Jackson `ObjectMapper`, but if this
> 
> ```java
> ZonedDateTime.parse("2020-Mar-24 01:41:11.000000000 UTC",
> DateTimeFormatter.ofPattern("yyyy-MMM-dd HH:mm:ss.SSSSSSSSS z")).withZoneSameLocal(ZoneId.of("UTC"))
> ```
> 
> throws an exception for you, then it must be something else.

I am curious about one thing, when I get a certain transaction on the ledger, it can be parsed correctly, and there is no problem with the time analysis!

**Comment by nkramer44** [comment]
I still cannot reproduce your error. xrpl4j uses Jackson v2.11.2, but I tried reproducing with Jackson v2.12.3 and didn't get an exception. 

Does this code fail for you?
```
ZonedDateTime.parse("2020-Mar-24 01:41:11.000000000 UTC",
DateTimeFormatter.ofPattern("yyyy-MMM-dd HH:mm:ss.SSSSSSSSS z")).withZoneSameLocal(ZoneId.of("UTC"))
```

What about this?
```
XrplClient xrplClient = new XrplClient(HttpUrl.get("https://s1.ripple.com:51234/"));
final LedgerResult ledger = xrplClient.ledger(
  LedgerRequestParams.builder()
    .transactions(true)
    .ledgerIndex(LedgerIndex.of("64190089"))
    .build()
);
    logger.info("Ledger: " + ledger);
```

Which JDK release are you on? I'm using adopt-openjdk8

**Comment by Smilestate** [comment]
> 我仍然无法重现您的错误。xrpl4j 使用 Jackson v2.11.2，但我尝试使用 Jackson v2.12.3 进行复制并没有出现异常。
> 
> 这段代码对你来说失败了吗？
> 
> ```
> ZonedDateTime.parse("2020-Mar-24 01:41:11.000000000 UTC",
> DateTimeFormatter.ofPattern("yyyy-MMM-dd HH:mm:ss.SSSSSSSSS z")).withZoneSameLocal(ZoneId.of("UTC"))
> ```
> 
> 那这个呢？
> 
> ```
> XrplClient xrplClient = new XrplClient(HttpUrl.get("https://s1.ripple.com:51234/"));
> final LedgerResult ledger = xrplClient.ledger(
>   LedgerRequestParams.builder()
>     .transactions(true)
>     .ledgerIndex(LedgerIndex.of("64190089"))
>     .build()
> );
>     logger.info("Ledger: " + ledger);
> ```
> 
> 您使用的是哪个 JDK 版本？我正在使用adopt-openjdk8

> ➜  ~ java -version
> java version "1.8.0_281"
> Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
> Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

**Comment by nkramer44** [comment]
Does this code fail for you?

```
ZonedDateTime.parse("2020-Mar-24 01:41:11.000000000 UTC",
DateTimeFormatter.ofPattern("yyyy-MMM-dd HH:mm:ss.SSSSSSSSS z")).withZoneSameLocal(ZoneId.of("UTC"))
```

**Comment by nkramer44** [comment]
Hey @Smilestate I'm going to close this for now. Feel free to reopen if this is still a problem for you.
