### ISSUE TITLE
ServerInfo: Jackson ZonedDateTime deserialization issue for Java 11+

### ISSUE THREAD

**Issue by enricohomann** [XRPLF/xrpl4j#156]
I just tested xrpl4j 2.1.0 with AdoptOpenJDK 11 and found a deserialisation issue with Jackson and the java.time.ZonedDateTime object in the ServerInfo model interface.

I also tested AdoptOpenJDK 14 with the same result. The code works fine with AdoptOpenJDK 8, though.

### pom.xml

		

		<dependency>
			<groupId>org.xrpl</groupId>
			<artifactId>xrpl4j-client</artifactId>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.xrpl</groupId>
			<artifactId>xrpl4j-address-codec</artifactId>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.xrpl</groupId>
			<artifactId>xrpl4j-keypairs</artifactId>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.xrpl</groupId>
			<artifactId>xrpl4j-model</artifactId>
			<version>2.1.0</version>
		</dependency>

### Minimal Code Fragment Sample

HttpUrl rippledUrl = HttpUrl.get("https://s.altnet.rippletest.net:51234/");
XrplClient xrplClient = new XrplClient(rippledUrl);
ServerInfo info = xrplClient.serverInfo();

### Expected Result

No exception

### Actual Result

org.xrpl.xrpl4j.client.JsonRpcClientErrorException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.ZonedDateTime` from String "2021-Sep-27 11:43:47.464662 UTC": Failed to deserialize java.time.ZonedDateTime: (java.time.format.DateTimeParseException) Text '2021-Sep-27 11:43:47.464662 UTC' could not be parsed at index 5
 at [Source: (String)"{"info":{"build_version":"1.7.2","complete_ledgers":"20262753-21365052","hostid":"SET","io_latency_ms":1,"jq_trans_overflow":"0","last_close":{"converge_time_s":2,"proposers":6},"load_factor":1,"peer_disconnects":"376062","peer_disconnects_resources":"109920","peers":123,"pubkey_node":"n9LXHjbYjz5byTrS5gf37WJj5XvdeXmdWCCJHL59wvpbXe5GT4f3","server_state":"full","server_state_duration_us":"9100832520576","state_accounting":{"connected":{"duration_us":"85045813","transitions":2},"disconnected":{"du"[truncated 476 chars]; line: 1, column: 702] (through reference chain: org.xrpl.xrpl4j.model.client.server.ImmutableServerInfoResult$Json["info"]->org.xrpl.xrpl4j.model.client.server.ImmutableServerInfo$Json["time"])
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:120)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:141)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy3.send(Unknown Source)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:93)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:141)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy3.send(Unknown Source)
	at org.xrpl.xrpl4j.client.XrplClient.serverInfo(XrplClient.java:244)
	at com.homannsoftware.xrpl4ft.XrplClientService.selfTest(XrplClientService.java:32)
	at com.homannsoftware.xrpl4ft.XrplClientService.main(XrplClientService.java:46)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.ZonedDateTime` from String "2021-Sep-27 11:43:47.464662 UTC": Failed to deserialize java.time.ZonedDateTime: (java.time.format.DateTimeParseException) Text '2021-Sep-27 11:43:47.464662 UTC' could not be parsed at index 5
 at [Source: (String)"{"info":{"build_version":"1.7.2","complete_ledgers":"20262753-21365052","hostid":"SET","io_latency_ms":1,"jq_trans_overflow":"0","last_close":{"converge_time_s":2,"proposers":6},"load_factor":1,"peer_disconnects":"376062","peer_disconnects_resources":"109920","peers":123,"pubkey_node":"n9LXHjbYjz5byTrS5gf37WJj5XvdeXmdWCCJHL59wvpbXe5GT4f3","server_state":"full","server_state_duration_us":"9100832520576","state_accounting":{"connected":{"duration_us":"85045813","transitions":2},"disconnected":{"du"[truncated 476 chars]; line: 1, column: 702] (through reference chain: org.xrpl.xrpl4j.model.client.server.ImmutableServerInfoResult$Json["info"]->org.xrpl.xrpl4j.model.client.server.ImmutableServerInfo$Json["time"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1702)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:947)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:129)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:235)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:50)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:118)
	... 12 more
Caused by: java.time.format.DateTimeParseException: Text '2021-Sep-27 11:43:47.464662 UTC' could not be parsed at index 5
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:229)
	... 30 more

### Potential Cause

Changes in the Date API of Java 11+

### Solution

?

**Comment by nkramer44** [comment]
Hey @enricohomann, I am unable to reproduce this error locally. Could you provide more detail on the following?

What is the exact JDK version you are using? I tried reproducing on the Tumerin AdoptOpenJdk 11 found here: https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot. 

What OS are you using?

Can you link to a GitHub project where this code is failing? 

Thanks

**Comment by enricohomann** [comment]
I tried a simple call to XrplClient.serverInfo() now with the latest AdoptOpenJDK 11.0.12.+7 with HotSpot under MacOS BigSur 11.6 and Windows 10 Pro as well. MacOS and Windows both showed the same issue.

> org.xrpl.xrpl4j.client.JsonRpcClientErrorException: com.fasterxml.jackson.databind.exc.InvalidFormatException:: Cannot deserialize value of type java.time.ZonedDateTime from String xxx

The error was first noticed in the following JUnit code snippet in our Spring Boot based project:

```
	@Test
	public void testGetXrplClient_ServerInfo() {
		/**
		 * # Check: There is an issue with ZonedDateTime an Jackson in Java 11 and above, that
		 * results in issues deserializing the Server Info entity. Works in Java 8
		 * though.
		 */
		try {
			XrplClient client = service.getXrplClient();

			// Client must not be null
			Assert.assertNotNull(client);

			// ServerInfo must not be null;
			ServerInfo serverInfo = client.serverInfo();
			Assert.assertNotNull(serverInfo);

			// Debug output
			System.out.println(serverInfo.toString());

		} catch (JsonRpcClientErrorException e) {
			e.printStackTrace();
			Assert.fail(e.getMessage());
		}

	}
```

The problem also appears in the following bare minimal example without Spring Boot:

```
public class XrplClientService {

	public static final String URL_ALTNET_TESTNET = "https://s.altnet.rippletest.net:51234/";

	private static final java.util.logging.Logger LOGGER = java.util.logging.Logger
			.getLogger(XrplClientService.class.getName());

	private XrplClient xrplClient;

	public XrplClient getXrplClient() throws JsonRpcClientErrorException {
		if (xrplClient == null || xrplClient.serverInfo() == null) {
			// Construct a network client
			HttpUrl rippledUrl = HttpUrl.get(URL_ALTNET_TESTNET);
			xrplClient = new XrplClient(rippledUrl);
		}
		return xrplClient;
	}

	public static void serverInfo() {
		try {
			HttpUrl rippledUrl = HttpUrl.get("https://s.altnet.rippletest.net:51234/");
			XrplClient xrplClient = new XrplClient(rippledUrl);
			ServerInfo info = xrplClient.serverInfo();

			LOGGER.log(Level.INFO, info.toString());
			LOGGER.log(Level.INFO, "Success");

		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.log(Level.INFO, "Failure");
		}
	}

	public static void main(String argv[]) {
		XrplClientService.serverInfo();
	}

}
```

**Comment by sappenin** [comment]
Hi @enricohomann, thanks for helping us diagnose this issue. Would you be able to try two more things for us?

1. Checkout the [xrpl4j-sample](https://github.com/XRPLF/xrpl4j-sample/) project and build it locally using `mvn clean package`. Does the project fail with the above error? (I recently introduced [a new test](https://github.com/XRPLF/xrpl4j-sample/blob/main/src/test/java/org/xrpl/xrpl4j/samples/ZonedDateTimeTests.java) to try to reproduce the issue, but it doesn't fail for me).

2. Checkout this project ([xrpl4j](https://github.com/XRPLF/xrpl4j/)) and build it using maven from the command line (e.g., `mvn clean package`). Does the project build for you, or does it fail?

Really appreciate your help here...
