### ISSUE TITLE
when signing: DecodeException: Version is invalid. Version bytes do not match any of the provided versions.

### ISSUE THREAD

**Issue by FFdhorkin** [XRPLF/xrpl4j#175]
I'm attempting to use xrpl4j from within Scala (sbt). I've tried all versions of xrpl4j 1.1 and newer.

Everything is working until I attempt to sign, using code that's basically the same as the tutorial (https://xrpl.org/send-xrp.html#4-sign-the-transaction-instructions):
```
// Sign transaction
val privateKey = PrivateKey.fromBase16EncodedPrivateKey(
    wallet.privateKey().get()
)
val signatureService = new SingleKeySignatureService(privateKey);

// Sign the Payment
val signedPayment = signatureService.sign(
    KeyMetadata.EMPTY,
    payment
)
```

Then I get this:

```
org.xrpl.xrpl4j.codec.addresses.exceptions.DecodeException: Version is invalid. Version bytes do not match any of the provided versions.
        at org.xrpl.xrpl4j.codec.addresses.AddressBase58.decode(AddressBase58.java:174)
        at org.xrpl.xrpl4j.codec.addresses.AddressBase58.decode(AddressBase58.java:112)
        at org.xrpl.xrpl4j.codec.addresses.AddressCodec.decodeAccountId(AddressCodec.java:91)
        at org.xrpl.xrpl4j.codec.binary.types.AccountIdType.fromJson(AccountIdType.java:38)
        at org.xrpl.xrpl4j.codec.binary.types.AccountIdType.fromJson(AccountIdType.java:13)
        at org.xrpl.xrpl4j.codec.binary.serdes.BinarySerializer.writeFieldAndValue(BinarySerializer.java:90)
        at org.xrpl.xrpl4j.codec.binary.types.STObjectType.lambda$fromJson$2(STObjectType.java:78)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.xrpl.xrpl4j.codec.binary.types.STObjectType.fromJson(STObjectType.java:76)
        at org.xrpl.xrpl4j.codec.binary.XrplBinaryCodec.encode(XrplBinaryCodec.java:61)
        at org.xrpl.xrpl4j.codec.binary.XrplBinaryCodec.encodeForSigning(XrplBinaryCodec.java:75)
        at org.xrpl.xrpl4j.crypto.signing.SignatureUtils.toSignableBytes(SignatureUtils.java:61)
        at org.xrpl.xrpl4j.crypto.signing.AbstractSignatureService.signWithBehavior(AbstractSignatureService.java:69)
        at org.xrpl.xrpl4j.crypto.signing.AbstractSignatureService.sign(AbstractSignatureService.java:54)
        ...
```

Any ideas?

**Comment by nkramer44** [comment]
Can you provide your full code snippet or a github repo? I'll try to reproduce this locally, but I've never encountered this problem when generating using a `WalletFactory`, which I'm assuming you are using. 

Also, which JVM are you running on?

**Comment by FFdhorkin** [comment]
I have figured out the issue: I was trying to use an X-Address for the destination address.

```
Payment payment = Payment.builder()
            .account(wallet.classicAddress())
            .amount(XrpCurrencyAmount.ofXrp(BigDecimal.ONE))
            .destination(Address.of(...)) // here was the issue. Was using Address.of on an X-address
            .sequence(sequence)
            .fee(openLedgerFee)
            .signingPublicKey(wallet.publicKey())
            .lastLedgerSequence(lastLedgerSequence)
            .build();
```

I needed to add this:
```
        AddressCodec addressCodec = AddressCodec.getInstance();
        XAddress xAddress = XAddress.of(...);
        ClassicAddress classicDestAddress = addressCodec.xAddressToClassicAddress(xAddress);
```
and then the payment signs correctly.

**Comment by nkramer44** [comment]
Ah cool, that makes sense. Glad you figured it out!
