### ISSUE TITLE
Jackson Parsing issues of transactions with TicketCreate

### ISSUE THREAD

**Issue by XRP-DEV** [XRPLF/xrpl4j#235]
Sologenic uses TicketCreate transactions. However if you try to fetch TicketCreate transactions it will always fail with a parsing error `No matching AccountSetFlag enum value for int value TicketCreate`.
 

Caused by: java.lang.IllegalArgumentException: No matching AccountSetFlag enum value for int value TicketCreate
	at org.xrpl.xrpl4j.model.transactions.TransactionType.forValue(TransactionType.java:120) ~[xrpl4j-model-2.2.0.jar:na]
	at org.xrpl.xrpl4j.model.jackson.modules.TransactionDeserializer.deserialize(TransactionDeserializer.java:31) ~[xrpl4j-model-2.2.0.jar:na]
	at org.xrpl.xrpl4j.model.jackson.modules.TransactionDeserializer.deserialize(TransactionDeserializer.java:17) ~[xrpl4j-model-2.2.0.jar:na]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4309) ~[jackson-databind-2.12.5.jar:2.12.5]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4265) ~[jackson-databind-2.12.5.jar:2.12.5]
	at org.xrpl.xrpl4j.model.jackson.modules.TransactionResultDeserializer.deserialize(TransactionResultDeserializer.java:45) ~[xrpl4j-model-2.2.0.jar:na]
	at org.xrpl.xrpl4j.model.jackson.modules.TransactionResultDeserializer.deserialize(TransactionResultDeserializer.java:29) ~[xrpl4j-model-2.2.0.jar:na]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[jackson-databind-2.12.5.jar:2.12.5]
	... 44 common frames omitted

**Comment by sappenin** [comment]
Hi @XRP-DEV, thanks for filing this issue!

Can you tell me which version of xrpl4j you're using? Thanks!

**Comment by nkramer44** [comment]
Hi @XRP-DEV, this should be fixed today. We have `Ticket` support in `main` but haven't cut a release yet. We will do that today and your issue should be fixed in version 2.3.0

**Comment by Smilestate** [comment]
When will 2.3.0 be released？

**Comment by sappenin** [comment]
It was just [released](https://github.com/XRPLF/xrpl4j/releases/tag/v2.3.0b). It will take a few hours to reflect in maven central. See [here](https://search.maven.org/artifact/org.xrpl/xrpl4j-crypto-parent) to confirm.

Closing this ticket as resolved. If v2.3.0 doesn't fix your issue, please re-open.

**Comment by XRP-DEV** [comment]
Awesome. Is there a (beer) donations page?

**Comment by sappenin** [comment]
Ha, not yet - we need to setup a tipbot account maybe! :)
