### ISSUE TITLE
Ledger problem?

### ISSUE THREAD

**Issue by Smilestate** [XRPLF/xrpl4j#242]
When I execute the ledger method to get the transaction, there is an exception!
The specific ledger is not sure, but an error is thrown. [code](https://github.com/XRPLF/xrpl4j/issues/239)
```java
org.xrpl.xrpl4j.client.JsonRpcClientErrorException: com.fasterxml.jackson.databind.JsonMappingException: No matching TransactionType enum value for String value UNLModify (through reference chain: org.xrpl.xrpl4j.model.client.ledger.ImmutableLedgerResult$Json["ledger"]->org.xrpl.xrpl4j.model.ledger.ImmutableLedgerHeader$Json["transactions"]->java.util.ArrayList[14])
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:120)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:141)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy130.send(Unknown Source)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:93)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:141)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy130.send(Unknown Source)
	at org.xrpl.xrpl4j.client.XrplClient.ledger(XrplClient.java:431)
	at bandex.wallet.chainlistener.XrpChainListener.transactionListener(XrpChainListener.java:132)
	at bandex.wallet.thread.BlockFecherRunnable.run(BlockFecherRunnable.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
I think the createticker enum was missing before and now the UNLModify enum is missing! 
```

**Comment by mukulljangid** [comment]
Hi! Thank you for bringing up this issue. Looks like pseudo transactions are not being recognized and parsed. There is a PR that adds them to the enum and deserializes them. See here: https://github.com/XRPLF/xrpl4j/pull/234

**Comment by mukulljangid** [comment]
This issue was addressed in the PR mentioned in the comment above, hence closing this. Feel free to re-open if any of this breaks.
