### ISSUE TITLE
this module can support android device?   No field IMPL_LOOKUP in class Ljava/lang/invoke/MethodHandles$Lookup

### ISSUE THREAD

**Issue by zhoushuntong** [XRPLF/xrpl4j#244]
when I run some demo on android device,  I get some Error like this:

     Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field IMPL_LOOKUP in class Ljava/lang/invoke/MethodHandles$Lookup; (declaration of 'java.lang.invoke.MethodHandles$Lookup' appears in /system/framework/core-oj.jar)
        at feign.DefaultMethodHandler.<init>(DefaultMethodHandler.java:46)
        at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:57)
        at feign.Feign$Builder.target(Feign.java:269)
        at feign.Feign$Builder.target(Feign.java:265)
        at org.xrpl.xrpl4j.client.JsonRpcClient.construct(JsonRpcClient.java:60)
        at org.xrpl.xrpl4j.client.XrplClient.<init>(XrplClient.java:92)

**Comment by nkramer44** [comment]
Hi @zhoushuntong, which version of xrpl4j are you using, and which JDK does your app run on?

**Comment by sappenin** [comment]
Closing this issue for now since it seems to no longer be an issue as of v2.2.0. If this is still an issue, please re-open.
