### ISSUE TITLE
XrplBinaryCodec decode should skip sig prefixes

### ISSUE THREAD

**Issue by manthanhd** [XRPLF/xrpl4j#278]
The following code:

```java
    final XrplBinaryCodec binCodec = new XrplBinaryCodec();
    final ObjectMapper objectMapper = ObjectMapperFactory.create();
    final SignatureUtils sigutils = new SignatureUtils(objectMapper, binCodec);
    final UnsignedByteArray unsignedTx = sigutils.toSignableBytes(payment);
// -- snip --
    final Transaction tx = objectMapper.readValue(binCodec.decode(unsignedTx.hexValue()),
        Transaction.class);
```

should work in a test but instead it throws the following error on `binCondec.decode`:

```
java.lang.Error: Cannot read FieldOrdinal, field_code out of range

	at org.xrpl.xrpl4j.codec.binary.serdes.BinaryParser.readFieldHeader(BinaryParser.java:136)
	at org.xrpl.xrpl4j.codec.binary.serdes.BinaryParser.readField(BinaryParser.java:149)
	at org.xrpl.xrpl4j.codec.binary.types.STObjectType.fromParser(STObjectType.java:45)
	at org.xrpl.xrpl4j.codec.binary.types.STObjectType.fromParser(STObjectType.java:23)
	at org.xrpl.xrpl4j.codec.binary.serdes.BinaryParser.readType(BinaryParser.java:164)
	at org.xrpl.xrpl4j.codec.binary.XrplBinaryCodec.decode(XrplBinaryCodec.java:135)
```

It is because it is not skipping the 8 hex characters prefixed during `sigutils.toSignableBytes -> binCodec.encodeForSigning` call. Thus, one has to do the following instead:

```java
    final Transaction tx = objectMapper.readValue(binCodec.decode(unsignedTx.hexValue().substring(8)),
        Transaction.class);
```

Note the substring skipping the first 8 hex characters.

Since the `XrplBinaryCodec` adds the prefix on `encode`, it should skip it on `decode`.

**Comment by sappenin** [comment]
@mukulljangid Please take a look at this one?

**Comment by mukulljangid** [comment]
the PR has been merged. Hence closing this issue! Feel free to reopen if you still have or find any other issues.
