### ISSUE TITLE
org.xrpl.xrpl4j.client.JsonRpcClientErrorException: Not supported field 'full'

### ISSUE THREAD

**Issue by milotj** [XRPLF/xrpl4j#538]
org.xrpl.xrpl4j.client.JsonRpcClientErrorException: Not supported field 'full'
	at org.xrpl.xrpl4j.client.JsonRpcClient.checkForError(JsonRpcClient.java:160)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:141)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy367.checkForError(Unknown Source)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:138)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:141)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy367.send(Unknown Source)
	at org.xrpl.xrpl4j.client.JsonRpcClient.send(JsonRpcClient.java:114)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:141)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy367.send(Unknown Source)
	at org.xrpl.xrpl4j.client.XrplClient.ledger(XrplClient.java:675)

**Comment by sappenin** [comment]
Hi, can you give more details:

1. Which network were you trying to connect to?
2. What request did you make?

**Comment by sappenin** [comment]
Hello, this appears to be a bug in Ripple's s1.ripple.com endpoint. That team is investigating and working on a fix. In the meantime, some options would be:

1. Run your own rippled node and communicate with that.
2. Use a different endpoint provider (e.g., Quicknode, XRPL Cluster, etc).

**Comment by hyeongcheolkim** [comment]
I have same issue.

**Comment by sappenin** [comment]
Quick update here - Ripple has reverted the latest deploy of Clio for s1/s2.ripple.com. The testnet should also be unaffected.

> I have same issue. I use Quicknode, xrpl4j 3.2.1 version.

Thanks @hyeongcheolkim - I'll reach out to Quicknode and let them know.

**Comment by sappenin** [comment]
I'm going to close this issue. Quicknode has been alerted, and it may take time for them or other infra providers to roll-back to the previous Clio release. In addition, https://github.com/XRPLF/clio/issues/1537 tracks the clio fix (already merged, will ship with next release). Finally, I've created https://github.com/XRPLF/xrpl4j/issues/540 as a tracking issue for when xrpl4j adds support for future Clio APIs.

That said, please feel free to re-open this ticket if needed.
